### ISSUE TITLE
DefaultRegistryCleaner runs in O(n) space

### ISSUE THREAD

**Issue by mahlingam** [apereo/cas#1199]
DefaultRegistryCleaner algorithm for iterating through the union set of TGT and ST does not scale, i.e.  in conjunction with long term authentication.
A viable solution must run in O(1) space, which might be implemented using a paging iterator pattern:
- Extend IF TicketRegistry with paging methods, 

``` java
    Collection<Ticket> getTicketGrantingTickets(int first, int pagesize);
    Collection<Ticket> getServiceTickets(int first, int pagesize);
```
- DefaultTicketRegistryCleaner::clean:

``` java
...
            Collection<PagingTicketProvider> pagingTicketProviders = new ArrayList<>();
            pagingTicketProviders.add(new PagingTicketProvider() {
                @Override
                public Collection<Ticket> nextPage(int firstResult, int pageSize) {
                    return ticketRegistry.getServiceTickets(firstResult, pageSize);
                }
            });
            pagingTicketProviders.add(new PagingTicketProvider() {
                @Override
                public Collection<Ticket> nextPage(int firstResult, int pageSize) {
                    return ticketRegistry.getTicketGrantingTickets(firstResult, pageSize);
                }
            });

            int pageSize = getPageSize();

            for (PagingTicketProvider pagingTicketProvider : pagingTicketProviders) {
                int firstResult = 0;
                boolean done = false;
                while (!done) {
                    Collection<Ticket> ticketsInCache = pagingTicketProvider.nextPage(firstResult, pageSize);
                    if (ticketsInCache.size() < pageSize) {
                        done = true;
                    }
                    firstResult = firstResult - removeTickets(ticketsInCache) + pageSize;
                    if (done) {
                        break;
                    }
                }
            }
...
```

**Comment by leleuj** [comment]
Indeed, the algorithm could be improved, but I'm not sure you can change all ticket registries to support the proposed new methods.

**Comment by battags** [comment]
I had a change (with one API addition) that offloaded the "calculation" and "cleanup" to the ticket registries themselves.  Basically you asked the registry to clean itself, which in some cases (memached) was a no-op and in other cases (JPA) used pagination.

**Comment by frett** [comment]
We have a customization in place in our deployment similar to what @battags mentioned. The main reason we implemented a self-cleaning `TicketRegistry` was memory usage of the JPA registry (it has to load all tickets into memory before it starts cleaning).

The things I don't care for about our current solution are:
1. There is a dependency cycle between the `CentralAuthenticationService` and `TicketRegistry` because we want to trigger logouts from our cleaning logic (done via `CentralAuthenticationService.deleteTicketGrantingTicket`) and the `CentralAuthenticationService` will contain the `TicketRegistry` itself. This has potential to muck with spring wiring especially when AOP is being utilized.
2. Duplication of the cleaning logic into our `TicketRegistry` and into any other `TicketRegistry` that implements the self cleaning concept.

I think the proposed paging solution would work better, but it should be an additional optional interface that could be implemented by any `TicketRegistry` that wants to utilize the functionality. I might toss together a PR implementing this optional behavior for the `JpaTicketRegistry` if I have time.

**Comment by mmoayyed** [comment]
@frett Interested to take this one? We could start with `JpaTicketRegistry` and then attempt to generalize.

**Comment by frett** [comment]
Yeah, i had been thinking about tossing a patch together for this and what it would look like to generalize it for any registry.

Some of this has changed with the cleaning process having been moved into individual registries now.

**Comment by frett** [comment]
now that we have switched to Java 8, this could be handled using the `Stream` API on top of some sort of paged loading.

Provide a `TicketRegistry.stream()` method with a default implementation that returns `getTickets().stream()`. Then override this implementation within specific TicketRegistries that can't load all the tickets into memory.

**Comment by frett** [comment]
article about the possibility of wrapping some Hibernate specific APIs into the java `Stream` API.

http://blog.informatech.cr/2014/12/17/java8-jpa-streams/

**Comment by mmoayyed** [comment]
Very cool. Looks promising.

**Comment by frett** [comment]
initial implementation of streaming tickets: https://github.com/frett/cas/tree/ticketCleaner

I need to spin this up and test with an actual database full of expired tickets to see if I need to tweak anything with memory usage before submitting a PR

**Comment by mmoayyed** [comment]
Awesome. 

Quick review: wouldnt it make sense to just change the way getTickets() works? since we are moving towards 5, I think that would be a valid change to change that signature.

**Comment by frett** [comment]
I'm going to try and swing back around to this within the next week or so and get a PR up. I'm going to fully replace the getTickets() method like you suggested since this is a major version release and we can make breaking changes. I like the idea and it makes sense that we prefer referencing tickets in a more memory friendly way.

**Comment by mmoayyed** [comment]
@frett Bumped into this issue today with Hazelcast. Lets talk more on the next dev call about what options we might want to consider. I think we need to come up with a way to build pagination into the ticket API natively, specially for the `getTickets()` call and since we are marching towards 5, this might be the perfect opportunity to do so.

**Comment by frett** [comment]
k, I'm assuming since pagination would in theory work, converting to the stream API should work (it could just iterate over the pages on demand)

**Comment by mmoayyed** [comment]
Yup or we should design it so it works that way if needed.

**Comment by mmoayyed** [comment]
Closing, due to inactivity and absence of demand. Can be revisited later if need be.
