### ISSUE TITLE
add dynamic registration of Ticket/OAuth types to JpaTicketRegistry

### ISSUE THREAD

**Issue by frett** [apereo/cas#1502]
We currently have a hardcoded dependency on the OAuth module for the `JpaTicketRegistry`. There needs to be a way to dynamically add supported models to the ticket registry

**Comment by leleuj** [comment]
Notice we have two OAuth modules, the dependency is on the core one which only holds tokens definitions and constants (not the web one).

**Comment by waronlive** [comment]
it was resolved

**Comment by mmoayyed** [comment]
This issue needs to be resolved before we can tackle and accept: https://github.com/apereo/cas/pull/2361

https://github.com/apereo/cas/pull/2361 attempts to separate HZ maps by running regex pattern checks on ticket id prefixes, which will limit use of the registry if and when OAuth ticket types are used.

**Comment by mmoayyed** [comment]
I reviewed this furthermore; Turns out that today; as Jérôme mentions there is only a dependency to the OAUTH core module and not the actual OAUTH functionality. Which lessens the impact of this issue (Using JPA does not mean OAUTH is enabled, etc). Furthermore, given the structure and hierarchy of OAUTH tickets and use of JPA annotations and the behavior of EntityManager etc, reworking support for this sort of thing where ticket types are utilized dynamically seems way too much for little gain. So I am going to close this for the time being, unless there are much louder complaints and better demand/use cases that would warrant spending more time on this issue.

**Comment by mmoayyed** [comment]
Of course, we still need to find an adequate solution for the way #2361 deals with ticket types and HZ maps, etc.
