### ISSUE TITLE
Consider moving project to Apereo org

### ISSUE THREAD

**Issue by dima767** [apereo/cas#1719]
For v5, consider moving project's remote from Jasig organization to Apereo organization: https://github.com/apereo

**Comment by frett** [comment]
+1

If you use the "Transfer ownership" option under the repo settings, it will link the old location to the new one, and maintain correct fork hierarchy. We've had to do this at work with a few of our repos that were under a different Github organization.

**Comment by frett** [comment]
it will also redirect git requests to the old origin URL to the new one. It makes the move seamless.

**Comment by mmoayyed** [comment]
Also a +1, though I think we should coordinate with Apereo at large to see if there is a plan, and whether we can make a move like this on our own. I'd also be interested to what happens to the docs site and the travis build as far as encryption settings go. Not sure if those auto transfer as well.

**Comment by dima767** [comment]
wrt docs - I am personally not a big fan of the current way the docs look and feel at GH pages. Are there any other docs rendering/hosting options out there we could look into for v5?

**Comment by mmoayyed** [comment]
There is readthedocs, but it's not quite what we need it to be. The main motivation I think is to make sure:

1. We control the documentation to some degree, so that unexpected edits don't happen with at-times wrong instructions. (But of course, we can be wrong too!) 
2. Code + documentation is in one place, updated in the same changeset. Otherwise, it's non-functional. 
3. GH Pages are designed for this kind of thing exactly, and we have automated processes that handle it all. It can be clunky, but you get what you pay for (or in this case, nothing!) 

Of course look and feel right now is horrible, and just a bad user experience over all. Once we get that fixed, other issues probably pale away. Might also be an item to work on prior to v5

**Comment by dima767** [comment]
I don't mind GH pages and our existing process of markdown-based docs near the code. If we somehow could fix/improve UX/look and feel and keep the existing process, I'll be a happy camper ;-)

**Comment by leleuj** [comment]
+1

**Comment by robertoschwald** [comment]
Maybe switch to [asciidoctor Gradle plugin](http://asciidoctor.org/docs/asciidoctor-gradle-plugin/), as I for example use in a Grails plugin: [Example](https://github.com/robertoschwald/grails-audit-logging-plugin/tree/master/audit-logging/src/docs)

Generating the docs is similiar to the current process, by creating in Travis and pushing into a branch.

Advantage is that it can create HTML, PDF and EPub at the same time and is [nice looking](https://robertoschwald.github.io/grails-audit-logging-plugin/latest/plugin.html) (in my opinion)

**Comment by dima767** [comment]
I like this look and feel!
