### ISSUE TITLE
Remove cas-server-support-console

### ISSUE THREAD

**Issue by dima767** [apereo/cas#1813]
Strongly consider removing `cas-server-support-console` subproject as similar capability is provided by Boot's remote shell subsystem and then some, out of the box: http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-remote-shell.html

My reasoning is well-known: 1) Don't re-invent the wheel 2) Less custom code to maintain == less bugs; less liability. 3) Use best tools available out there.

**Comment by dima767** [comment]
Good. I'll get to it today

**Comment by mmoayyed** [comment]
Caveat: Remove all the code, but not the module perhaps. Not sure yet, but we probably would want to have the module pull in the right boot dependencies and make them streamlined with other config and we probably may want to make the behavior of the module a bit more CAS specific. Otherwise, it would be up to the overlay to configure things.

**Comment by dima767** [comment]
I'd personally lean towards - just leave it up to overlay/local build to configure Boot's shell. Besides, this kind of a need (get into the server internals via remote shell) would be a "niche" use case, etc.

**Comment by dima767** [comment]
But sure, I'll remove the code, PR, and we take it from there...

**Comment by mmoayyed** [comment]
I don't mind the overlay to make the decision on whether a shell is required or not. But I don't want the overlay to configure the internals of the shell configuration. I would not want an adopter to figure out which boot module must go in, what boot version, how to resolve conflicts, how to configure things, where to find docs on this stuff, who maintains the docs, etc. All they should need to do is declare a single CAS module that [re]configures everything needed. If the adopter needs it, they can always declare or undeclare the module, but they should not have to do any more than that. This is similiar to how we do things with Spring session where CAS modules simply act as mere wrappers, enabling/massaging functionality already available. (Another advantage of the module is that it makes it more of a "CAS feature", rather than a "boot feature" which is a big :trophy:  )

**Comment by dima767** [comment]
+1
