### ISSUE TITLE
Management Service does not take into accompt "required Handler"

### ISSUE THREAD

**Issue by vieville** [apereo/cas#1851]
Hi Misagh,

I run on tomcat 8 and CAS 4.2

Despiste of setting "tryAll" boolean and declaring two authentication handlers, CAS did not try the second authentication handler
I have modified the code of authenticationmanager to set one credential for each valid authentication handler.
I push my overlay into an issue

Thank you

Claude

**Comment by mmoayyed** [comment]
Thanks for passing on the overlay. I'll take a look later today.

**Comment by dima767** [comment]
Overlay: https://github.com/cas-projects/cas-issues/tree/master/cas-issue-1851

**Comment by mmoayyed** [comment]
CAS will never try the 2nd authentication handler if it succeeds on the first try, by default. The authentication policies dont quite deal with trying multiple handlers; they are more related to multiple sets of credentials (Think MFA). 

If you want the authentication event to succeed ONLY IF when a given handler is tried (and is successful), you need to

change

```
<alias name="anyAuthenticationPolicy" alias="authenticationPolicy"/>
```

to

```
<alias name="requiredHandlerAuthenticationPolicy" alias="authenticationPolicy"/>
```

And define the handler:

```
cas.authn.policy.req.handlername=whatever-the-handler-name-is.
```

**Comment by mmoayyed** [comment]
v5 takes this one step further; If you set `requiredHandlerAuthenticationPolicy`, all authentication handlers in 4.x are tried until a successful match is produced or not. Sometimes however, YOU KNOW what handler you want to associate with a given service and you want ONLY that handler to execute (rather than trying them all and forcing a condition after the fact). This is now possible with 5.

**Comment by dima767** [comment]
Another reason why v5 is awesome! ;-)
