### ISSUE TITLE
STs that are attached to a TGT are not counted in total ticket cleanup

### ISSUE THREAD

**Issue by featheredtoast** [apereo/cas#1969]
...while using the default ticket registry. This results in inconsistent ticket count reporting while cleaning.
Cleanup for 5 separate logins (5 TGTs + 5 STs), cleaner reports ~7-9 tickets cleaned.

Re-attaching the log file for reference.
[cas.zip](https://github.com/apereo/cas/files/437531/cas.zip)

CAS 4.2.5-SNAPSHOT
Tomcat 7, Java 8.
https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/ZMerMRq_EWg

**Comment by mmoayyed** [comment]
@wcrowell since you did some recent work with the cleaner, would you be interested to handle this issue as well? I think we are supposed to go to 4.2.5 in about a week. But there is no rush, as it's just a minor logging problem.

The patch likely needs to be ported to 5 too.

**Comment by wcrowell** [comment]
@mmoayyed Sure, I can start looking at it now.  Was just messing around with the Couchbase Lite Java Listener, but I can put that on hold.

**Comment by mmoayyed** [comment]
Excellent. Thanks.

**Comment by wcrowell** [comment]
@mmoayyed Here is what is happening...when org.jasig.cas.ticket.registry.TicketRegistryCleaner's execute method is run it gets a collection of all tickets (expired and unexpired).  The order of the collection is not guaranteed.  If the TGTs are iterated at the beginning, then it deletes the TGT and any children of the TGT which include STs.  This means the collection is modified while the apply method is still iterating through the collection.  The child tickets are not included in the total and that explains why the total is off.  It would be ideal if the deleteTicket method in the org.jasig.cas.ticket.registry.TicketRegistry interface return the cumulative amount of tickets that were deleted.  Since we are so close to the 4.2.5 release, I am not sure if you would want the method signature changed.  We could call the deleteSingleTicket(String) on org.jasig.cas.ticket.Ticket.AbstractTicketRegistry but you would either need to cast to AbstractTicketRegistry:

`((AbstractTicketRegistry) registry).deleteSingleTicket(ticket.getId());`

or the deleteSingleTicket method could be promoted up to the org.jasig.cas.ticket.registry.TicketRegistry interface.

Thoughts on this?

**Comment by mmoayyed** [comment]
> It would be ideal if the deleteTicket method in the org.jasig.cas.ticket.registry.TicketRegistry interface return the cumulative amount of tickets that were deleted

Yes, this is what I'd do.

**Comment by wcrowell** [comment]
Just did a PR.  Please take a look when you get a moment.  Thanks.

**Comment by mmoayyed** [comment]
This is merged and should be available in 4.2.5-SNAPSHOT in an hour or so. I'll keep the issue open until we have ported the same patch forward to master/5 as this is considered a bug.
