### ISSUE TITLE
[MFA] - Let GAuth keep track of and reject previously used tokens

### ISSUE THREAD

**Issue by lsenecaux** [apereo/cas#2042]
I think that the actual implementation of mfa-gauth can provide a security issue.
In fact, the window size in application.properties should be used to compensate clock difference between server and clients, and not to permit the reusage of the same token.
Then, the backend registry (jpa) should retain the tokens that were previously used.
In this way, it will be impossible for a hacker (in the case of man in the middle attack) to replay the authentication.

Regards,

**Comment by mmoayyed** [comment]
Thinking more about this:

1. Who is in charge of cleaning up the database? `If the backend registry (jpa) should retain the tokens that were previously used.`, then what happens when the database grows to a billion records over time?
2. Suppose today I created an TOTP that is 123-456. Used it. Recorded it. Is there any chance, 9 months from now, that I end up regenerating the same token which would then be considered invalid?

**Comment by frett** [comment]
I glanced at the TOTP spec a few months ago, if I remember correctly the spec actually says that after you use a token for a specified time code you can't use any earlier tokens.

So, a better mechanism might be to just track the last used token time. Once a user authenticates using the token for timecode 50, they need to use the token for timecode 51 at least.

**Comment by lsenecaux** [comment]
1. The registry must be in charge of cleaning up the database.

2. I think we should store the timestamp that was used to create the token instead of the token itself. Then, the window size should help to clean some records.
Generation of the token is based on time divided by 30, so the registry should store this value.
When a user logs on, the registry should remove the records whose values are less than ((timestamp + floor (windowSize / 2) * -1 * 30) / 30).

I hope I was enough clear in my explanation

**Comment by mmoayyed** [comment]
Handled in RC2
