### ISSUE TITLE
OIDC implicit/token profile

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2065]
Evaluate the current OIDC support in CAS to determine whether implicit profile can be supported. It may already be, but we’ll need to make sure and document nuances. Discuss with @leleuj

**Comment by leleuj** [comment]
It should work as the OAuth 2.0 support handles it, but I need to test it to be sure.

**Comment by raymondBourges** [comment]
I do some tests and it's not yet supported :

I use cas-gradle-overlay-template with 5.0.3-SNAPSHOT CAS version because of #2333

I add :
    compile "org.apereo.cas:cas-server-support-oidc:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-json-service-registry:${project.'cas.version'}"

In OIDC doc about implicit flow (http://openid.net/specs/openid-connect-implicit-1_0.html#RequestParameters), the response_type request parameter is “REQUIRED. This value consists of id_token and token, as a space-delimited list.”

With a service :

servimplicit-1.json :
{
  "@class" : "org.apereo.cas.services.OidcRegisteredService",
  "clientId": "servimplicit",
  "serviceId" : "^https://localhost:8443/test",
  "signIdToken": true,
  "name": "servimplicit",
  "id": 1,
  "evaluationOrder": 100
}

A GET on https://cas.cocktail.fr:8443/cas/oidc/authorize?response_type=id_token%20token&client_id=test&redirect_uri=https://localhost:8443/test&scope=openid%20profile&state=af0ifjsldkj&nonce=n-0S6_WzA2Mj
log "ERROR [org.apereo.cas.web.controllers.OidcAuthorizeEndpointController] - <Unsupported response type: id_token token>"

**Comment by raymondBourges** [comment]
My use case : A angular front requesting a java/rest back-end. Front use a JWT to carry auth information to back-end. Today front obtain JWT in a non standard way. I want to use CAS as an OIDC server to obtain this JWT.

I am ok to test implicit flow as soon as implemented.

I will try to have a look on code but not sure I can make a pull request because of lack of time and competence but I will try...

**Comment by mmoayyed** [comment]
Thank you @raymondBourges I adjusted the milestone to note that this will be covered in 5.1.

**Comment by raymondBourges** [comment]
I saw some commits yesterday.

I test on master and it seems ok. Great job :)

I will test deeper asap.

Thanks

**Comment by raymondBourges** [comment]
2 problems against specification:

With a service servimplicit-1.json:
{
  "@class" : "org.apereo.cas.services.OidcRegisteredService",
  "clientId": "servimplicit",
  "serviceId" : "^https://localhost:8443/test",
  "signIdToken": true,
  "implicit": true,
  "name": "servimplicit",
  "id": 1,
  "evaluationOrder": 100
}

A GET on https://cas.cocktail.fr:8443/cas/oidc/authorize?response_type=id_token%20token&client_id=servimplicit&redirect_uri=https://localhost:8443/test&scope=openid%20profile&state=af0ifjsldkj&nonce=n-0S6_WzA2Mj

I obtain this jwt PAYLOAD:
{
  "jti": "2d6c294b-638f-4c67-8b6e-6c0de9e3dd08",
  "iss": "http://cas.cocktail.fr:8443/cas/oidc",
  "aud": "servimplicit",
  "exp": 1486299481,
  "iat": 1486292281,
  "nbf": 1486291981,
  "sub": "casuser",
  "amr": [
    "AcceptUsersAuthenticationHandler"
  ],
  "state": "af0ifjsldkj",
  "nonce": "n-0S6_WzA2Mj",
  "preferred_username": "casuser"
}

according http://openid.net/specs/openid-connect-implicit-1_0.html#IDToken
- iss should begin with "https" and not "http"
- at_hash is required

Thanks

**Comment by mmoayyed** [comment]
Excellent. Thanks for the feedback. The issuer is controlled by you via settings I believe. But at_hash , yes that should be fixed.

**Comment by raymondBourges** [comment]
You are right about issuer. It's a error in my settings. Excuse me.

**Comment by mmoayyed** [comment]
No worries. at_hash should now also be functional. Continue testing please :)
