### ISSUE TITLE
Saml IdP Metadata Location not parsed as uri/url

### ISSUE THREAD

**Issue by dacurry-tns** [apereo/cas#2108]
The [documentation](https://apereo.github.io/cas/development/installation/Configuration-Properties.html#saml-idp) says that the `cas.authn.samlIdp.metadata.location` property should be set to a uri/url like `file:/etc/cas/saml`.

However, if you do this, the server will die on startup with "Metadata directory location file:/etc/cas/saml cannot be located/created".  (You will get the same error if you use `file:///etc/cas/saml`.)

If you leave the property unset, everything works correctly. Likewise, if you set the property to a regular file system path like `/etc/cas/saml` (instead of `file:/etc/cas/saml`), everything works correctly.

**Comment by mmoayyed** [comment]
@dacurry-tns Do you prefer to submit a PR to correct this in the docs?

**Comment by dacurry-tns** [comment]
Um, well, I don't have anything forked at the moment (still working on getting the existing stuff running the way I want before adding customizations), but I suppose I could figure it out.

Is that the right place, though? I was assuming it was a bug in the code, not a bug in the doc, since there seems to be pretty consistent use of uri/url notation in other properties (and I'm not sure I'm enough of a Java person to know where to put it in that case).

But if it should be fixed in the doc, I'll take a stab at it.

**Comment by mmoayyed** [comment]
It really should be fixed in the code as well, but at this point, we are not planning to make any other changes. So we can fix the docs for now, and then later when get around to it we will fix both the docs and the code to account for full URI form.

The process is fairly simple. Find the doc, click the edit icon, fork it, edit it, create a PR right there. Click click click click :)

**Comment by mmoayyed** [comment]
Solved in 5.1
