### ISSUE TITLE
CAS 5.1.0-SNAP MFA bypass issue

### ISSUE THREAD

**Issue by pmarasse** [apereo/cas#2138]
Environment :
  - CAS Server 5.1.0-SNAP (maven overlay)
  - Container : Tomcat 8.5.8 / Java 1.8.0u111 / Debian 8 32 bits

I want to bypass yubikey MFA if SPNEGO auth already occurred. so in my cas.properties, I set : 
`cas.authn.mfa.yubikey.bypass.authenticationHandlerName=JcifsSpnegoAuthenticationHandler`

In this case, things seems to be reverted : 
  - Spnego triggers MFA and yubikey
  - Login form (Ldap Auth) does not trigger MFA

If I change the property to : 
`cas.authn.mfa.yubikey.bypass.authenticationHandlerName=LdapAuthenticationHandler`

I get the expected behaviour : 
  - Spnego does not trigger MFA
  - Login form triggers MFA

I attach two parts of the same log (with bypass set to JcifsSpnego) : 
  - [start and ldap auth](https://github.com/apereo/cas/files/602398/ldap-only.txt)
  - [spnego with unexpected MFA](https://github.com/apereo/cas/files/602400/spnego-yubi.txt)

**Comment by mmoayyed** [comment]
Please try with the latest snapshot.

**Comment by pmarasse** [comment]
It seems to work as expected now, thank you.

In #2126 you advised not to use `JcifsSpnegoAuthenticationHandler`, is there another way to specify a bypass when the first auth is SPNEGO ?

**Comment by mmoayyed** [comment]
Presently not. I was noting that we should make that alternative possible so you can define your own names rather than relying on the Java class name (which may change). So if you'd like to avoid that, do please create a separate issue and highlight the use case. The idea is to basically provide settings so adopters can define their own names for handlers, which then can be used for bypass. CAS already allows for such options at the API level, we just need to account for those in the auto-config strategy as well via the usual CAS properties.
