### ISSUE TITLE
Move to Java collections

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2212]
Issue created to track desired changes:

- use Java collections instead of Guava
- Review streams use, and try to make them a bit more functional
- Make a better use of optionals

**Comment by DavidRG13** [comment]
hey,

any ideas on how to replace ```Table``` in Cas-server-support-digest-authentication module?

**Comment by mmoayyed** [comment]
Or let me elaborate: are you referring to @Table annotations? Is there a reason those should be replaced?

**Comment by DavidRG13** [comment]
Sorry, I mean ```com.google.common.collect.Table``` in ```DefaultDigestHashedCredentialRetriever```

**Comment by mmoayyed** [comment]
Oh gotcha. I am not aware of any other data structures to replace it. Perhaps you need to write a Map whose key is a `Pair`?

**Comment by DavidRG13** [comment]
First of all, Is it worthy? 

Secondly, having a look into ```DigestAuthenticationConfiguration.defaultDigestCredentialRetriever()``` the second element of the key is always ```casProperties.getAuthn().getDigest().getRealm()```.
Maybe we just need a ```Map```. (maybe I'm missing something)

**Comment by mmoayyed** [comment]
Two things: 

- One "could" argue that this issue is mostly making sure Guava-based collections whose equivalent is found today in the java Collections API should be modified and ported over. There is no "easy" equivalent for Table. So it might be safe to skip for now. So in that sense, no it's probably not worth the effort/time.
- But, could the design be improved to entirely remove the need for Table and such? Always. Looking back, Map should work I think. We could tackle that under a separate issue of course, etc.

**Comment by DavidRG13** [comment]
soo.. let's replace the table with a map? separate issue or it's under this one?

**Comment by mmoayyed** [comment]
Yes, and separate. Thanks!

**Comment by DavidRG13** [comment]
Just an update.

There is only one ```InmutableSet``` standing!!! ^_^
I tried several times to replace it, but tests are failing... need some more time, but we are good!

**Comment by mmoayyed** [comment]
Awesome work!
