### ISSUE TITLE
Let string-column field lengths of registered services to remain at 255. 

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2250]
I am in the process of upgrading our CAS 3.5.2 to CAS 5.0.1 and I have a problem with the column lengths for String fields in org.apereo.cas.services.AbstractRegisteredService.

In CAS 3 and 4 these fields were set to length=255, but in CAS 5 they have been changed to length=Integer.MAX_VALUE.

The problem is that this produces a DDL script with VARCHAR(2147483647) columns, which is invalid in DB2 databases (and various other databases as well).

In DB2 the max length for a VARCHAR column is 32704, but there are other databases where the limit is as low as 255 (which is probably why CAS 3 and 4 contained that length).

Can this change be reverted or was there a specific reason for this change?

**Comment by mmoayyed** [comment]
Problem is that 255 and other various numbers are such "arbitrary numbers" that make it very difficult to reason about the length at an abstract level. That being said, I would:

1. Consult hibernate forums and see if there is something they might be able to do, as the annotation certainly does allow for a valid integer. Hibernate's job is to generate the DDL in a platform agnostic way, so we could in theory pass a length of -56 or 834562335 and it should be able to warn/error out or massage that to be the "right number". 
2. 255 probably works for 3 but certainly not for 4 and 5 versions specially when it comes to blobs. So in practice, we'd have to maintain this mental model of "255 works for fields A and B but not for C and D, except when it's database X with Driver Y, etc". It's simply not worth it, which brings me back to #1 that is, Hibernate should be able to help in this area. 
3. You're welcome to change things back to 255 if that works better. 
4. I am thinking perhaps, given such variations between database platforms and almost knowing Hibernate isn't going to solve this problem, or as quickly, perhaps we should allow options to define the max length for databases of choice. I really really do hate this option, (because again it feels like this is a semi-correct solving the wrong sort of problem) but ultimately that probably works best with all other platforms.

**Comment by Condor70** [comment]
1. Unfortunately, Hibernate isn't that smart. It doesn't take field length into account when determining a field type (VARCHAR vs CLOB).
2. My request is ONLY for the String fields. I have no problem with Binary fields marked with @Lob having a length of Integer.MAX_VALUE (CAS 4 already did it this way).
3. This is what i'm currently doing, but this complicates CAS upgrades.
4. I agree, it feels a bit "dirty". Alternatively, you could mark the fields with @Lob, but this creates large object fields which query slower. The best compromise still seems a length of 255 to me, because in the past nobody has complained about the field length.

**Comment by mmoayyed** [comment]
Sounds great. Is this something you might be willing to contribute back?

**Comment by Condor70** [comment]
OK, this was my first pull request ever. Did I do everything correctly?

**Comment by mmoayyed** [comment]
Yes. You did! Thanks! Keep it coming.
