### ISSUE TITLE
regression with MD5 encoded passwords in file or database

### ISSUE THREAD

**Issue by ppcamacho** [apereo/cas#2302]
According to gitter conversation at 2017.01.11 15:54 about regression
5.1.0-RC1 works, 5.0.1 and 5.0.2-SNAPSHOT not

configuration
```
cas.authn.accept.users=
cas.authn.file.separator=::
cas.authn.file.filename=file:/etc/cas/config/users.txt
cas.authn.file.passwordEncoder.type=DEFAULT
cas.authn.file.passwordEncoder.encodingAlgorithm=MD5
cas.authn.file.passwordEncoder.characterEncoding=UTF-8

cas.authn.jdbc.query[0].user=<...>
cas.authn.jdbc.query[0].password=<...>
cas.authn.jdbc.query[0].url=jdbc:mysql://localhost/authority
cas.authn.jdbc.query[0].sql=SELECT password FROM users WHERE login=?
cas.authn.jdbc.query[0].driverClass=com.mysql.jdbc.Driver
cas.authn.jdbc.query[0].healthQuery=SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
cas.authn.jdbc.query[0].passwordEncoder.encodingAlgorithm=MD5
cas.authn.jdbc.query[0].passwordEncoder.type=DEFAULT
cas.authn.jdbc.query[0].passwordEncoder.characterEncoding=UTF-8
```

file with user and password (md5 is testpass)

`user::179ad45c6ce2cb97cf1029e212046e81
`

**Comment by gabedwrds** [comment]
I came across this while working on #2229 but didn't have time to follow up on it... if I remember correctly the issue is that the JDBC authentication handler (and presumably some others) expects PasswordEncoder matches() functions to take the raw unencoded input as per the interface spec, but DefaultPasswordEncoder in 5.0.x right now just does a string comparison which expects both inputs to be encoded already.

It looks like the DefaultPasswordEncoder in master handles matches() correctly and might be simple to backport into 5.0.x.

**Comment by mmoayyed** [comment]
Fix in latest snapshot.
