### ISSUE TITLE
CAS 5 and bootRun on overlay failing after adding a dependency

### ISSUE THREAD

**Issue by dlbunker** [apereo/cas#2334]
CAS server version = 5.0.2
Container/environment type/version = Mac OSX using the ./gradlew bootRun command

**Steps to duplicate the problem**
1.  Simply clone the master of https://github.com/apereo/cas-gradle-overlay-template
2. run ./gradlew clean build bootRun (everything works great)
3. Add any dependency to cas/build.gradle like 'compile "org.apereo.cas:cas-server-support-json-service-registry:${project.'cas.version'}"'
4. re-run ./gradlew clean build bootRun
5. Failure when gradle runs :cas:bootRun portion of the build tasks

**Stacktraces and CAS logs where appropriate.**
Execution failed for task ':cas:bootRun'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

I've tried with 2 different JDK 1.8 versions with the same result.  Any suggestions to run with spring boot and dependencies like oath, JWT would be appreciated.

**Comment by dima767** [comment]
This is a known issue, and it is not a CAS' fault, per-se. Kind of complicated with Spring Boot's Gradle plugin and the Classpath size that CAS produces, etc. I believe currently it is unknown yet how to mitigate it, but we will keep this issue for tracking purposes.

Current workaround on running CAS from the command line in the embedded mode is to simply `java -jar cas/lbs/cas.war`

**Comment by dlbunker** [comment]
@dima767 ok Thanks.

**Comment by mmoayyed** [comment]
http://stackoverflow.com/questions/41736562/spring-boot-maven-gradle-plugin-bootrun-task-generates-very-long-classpath

**Comment by hdeadman** [comment]
I got around this issue by making a maven multi-project. In one sub-project I add dependencies I need and build the war for subsequent overlays. In the other sub-project I do configuration and do the war overlay again but don't add any new dependencies. 

- cas-parent - Root maven project, good place for Vagrantfile that allows testing on linux
- cas-parent/cas-war - Overlay dependencies on cas-server-webapp, making new base war
- cas-parent/cas-config - Customize via config and overlaying of resources, etc, but only dependency is the war from the other sub-project so mvn spring-boot:run works.

**Comment by mmoayyed** [comment]
@hdeadman Do you have an overlay based on that model you can share?

**Comment by hdeadman** [comment]
I checked in something to https://github.com/hdeadman/cas-overlay-template

You should be able to clone and run:
mvn install
cd cas-overlay-config
createcert.bat    (or look at contents and run platform equivalent command)
mvn spring-boot:run

I didn't use build.sh b/c I am on windows. I changed a couple things so it reads files from ./etc instead of requiring them to be copied to /etc. I also tweaked the log4j2.xml so it puts the logs in -Dcas.log.dir=target but if you don't specify the system property it will default to the current directory like it was before. Maven sets the system property to target but default property is in log4j2.xml.

There are some mvn profiles (casdebug, springdebug) that let you run with Java debugger options or the spring-boot --debug option. 

Relying on maven instead of build.sh makes it more platform independent. Of course I added a bat file but it's just a one-liner. 

I didn't update the readme but I could if you thought this was a useful direction. 

If you are were to cd into the cas-overlay-webapp folder and run mvn spring-boot:run you should get the java error, presumably b/c of classpath length (at least on windows). 

The set of dependencies I have in cas-overlay-webapp is just some of what I am using. I didn't add any of the configuration for the modules I included.

**Comment by mmoayyed** [comment]
As is explained by this issue https://github.com/spring-projects/spring-boot/issues/8320 our use of `bootRun` in an overlay mode is not something that Spring Boot can, will or should ever handle as the task is NOT ever designed to work with already-executable WARs. Our use in overlay projects simply just happens to remain slightly functional with luck, so I think we should deprecate the use of `bootRun` in overlay projects with enough and adequate disclaimers and encourage folks to either use `java -jar`, or external tomcat deployments. 

Note that `bootRun` on the CAS codebase remains perfectly functional as it's designed to do what it was meant to do. One may also want to adopt the solution https://github.com/hdeadman/cas-overlay-template provided by @hdeadman (thank you by the way), and we can use this issue and that link as a reference for those WHO REALLY may want to experiment with `bootRun`.

However, we might be able to use `bootRun` with the Gradle DSL: https://github.com/apereo/cas/issues/2069

**Comment by mmoayyed** [comment]
Warnings and disclaimers added to the overlay projects' READMEs.
