### ISSUE TITLE
5.0.x can't init JPA service registry

### ISSUE THREAD

**Issue by michal-n** [apereo/cas#2424]
CAS server webapp can't initialize JPA Service Registry in PostgreSQL for me. It fails to create tables. DB setup seems OK, as the webapp does properly create and fill tables for JDBC audit logs.

I tried older versions in 5.0.x series. CAS-webapp 5.0.0 can create *some* tables, but fails at *regexregisteredservice* and crashes. All newer 5.0.x versions can't do even that.

I then tried with CAS-management 5.0.3.1 and it worked like a charm. Tables created. But CAS server webapp still wouldn't start. I had to downgrade it to 5.0.1 - no higher 5.0.x version can actually use the tables.

CAS server version: 5.0.0 ... 5.0.3.1

Java: 1.8.0_101
Container: default embedded Tomcat
OS: Ubuntu 16.04.2, kernel 4.4.0-65
Database: PostgreSQL 9.5.6

My settings for CAS-webapp (work for 5.0.0 and 5.0.1, fail for later, up to and including 5.0.3.1):

```xml
<dependency>
	<groupId>org.apereo.cas</groupId>
	<artifactId>cas-server-support-jdbc-drivers</artifactId>
	<version>${cas.version}</version>
</dependency>
<dependency>
	<groupId>org.apereo.cas</groupId>
	<artifactId>cas-server-support-audit-jdbc</artifactId>
	<version>${cas.version}</version>
</dependency>
<dependency>
	<groupId>org.apereo.cas</groupId>
	<artifactId>cas-server-support-jpa-service-registry</artifactId>
	<version>${cas.version}</version>
</dependency>
```

```ini
# service registry
cas.serviceRegistry.initFromJson=false    # I rely on CAS-management now
#cas.serviceRegistry.initFromJson=true    # Tried to use this to self-initialize
cas.serviceRegistry.jpa.ddlAuto=none      # I rely on CAS-management now
#cas.serviceRegistry.jpa.ddlAuto=create   # Tried to use this to self-initialize
cas.serviceRegistry.jpa.healthQuery=select 1
cas.serviceRegistry.jpa.isolateInternalQueries=false
cas.serviceRegistry.jpa.driverClass=org.postgresql.Driver
cas.serviceRegistry.jpa.dialect=org.hibernate.dialect.PostgreSQL94Dialect
cas.serviceRegistry.jpa.url=jdbc:postgresql://localhost/db
cas.serviceRegistry.jpa.user=dbuser
cas.serviceRegistry.jpa.password=dbpass

# Audit logging - works fine!
cas.audit.jdbc.ddlAuto=none               # Used 'create' for first run
cas.audit.jdbc.healthQuery=select 1
cas.audit.jdbc.driverClass=org.postgresql.Driver
cas.audit.jdbc.dialect=org.hibernate.dialect.PostgreSQL94Dialect
cas.audit.jdbc.url=jdbc:postgresql://localhost/db
cas.audit.jdbc.user=dbuser
cas.audit.jdbc.password=dbpass
cas.audit.jdbc.maxAgeDays=3653

# tell me more
logging.level.org.hibernate=DEBUG
```

Settings for CAS-management (I tried only 5.0.3.1, it works fine for me):

```xml
<dependency>
	<groupId>org.apereo.cas</groupId>
	<artifactId>cas-server-support-jdbc-drivers</artifactId>
	<version>${cas.version}</version>
</dependency>
<dependency>
	<groupId>org.apereo.cas</groupId>
	<artifactId>cas-server-support-jpa-service-registry</artifactId>
	<version>${cas.version}</version>
</dependency>
```

```ini
# service registry
cas.serviceRegistry.initFromJson=false          # Used 'true' for first run
cas.serviceRegistry.jpa.ddlAuto=none            # Used 'create' for first run
cas.serviceRegistry.jpa.healthQuery=select 1
cas.serviceRegistry.jpa.isolateInternalQueries=false
cas.serviceRegistry.jpa.driverClass=org.postgresql.Driver
cas.serviceRegistry.jpa.dialect=org.hibernate.dialect.PostgreSQL94Dialect
cas.serviceRegistry.jpa.url=jdbc:postgresql://localhost/db
cas.serviceRegistry.jpa.user=dbuser
cas.serviceRegistry.jpa.password=dbpass
```

**Comment by michal-n** [comment]
[cas-5.0.3.1-console-log.txt](https://github.com/apereo/cas/files/813702/cas-5.0.3.1-console-log.txt)
[cas-5.0.0-console-log.txt](https://github.com/apereo/cas/files/813703/cas-5.0.0-console-log.txt)

**Comment by mmoayyed** [comment]
I ran this setup agains 5.0.4 SNAPSHOT with the following properties:

```
cas.serviceRegistry.jpa.healthQuery=
cas.serviceRegistry.jpa.url=jdbc:postgresql://localhost:5432/postgres
cas.serviceRegistry.jpa.dialect=org.hibernate.dialect.PostgreSQL94Dialect
cas.serviceRegistry.jpa.user=postgres
cas.serviceRegistry.jpa.ddlAuto=create-drop
cas.serviceRegistry.jpa.password=postgres
cas.serviceRegistry.jpa.driverClass=org.postgresql.Driver
```

Running against postgres:9.5.5-alpine.

CAS came up just fine. Please investigate the issue further and file a pull request if necessary to fix the problem.

**Comment by amoscatelli** [comment]
The issue is still present :

`2017-10-30 14:16:23,014 INFO [org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration] - <Located property source: PropertiesPropertySource {name='standaloneCasConfigService'}>
2017-10-30 14:16:23,019 INFO [org.apereo.cas.web.CasWebApplicationServletInitializer] - <The following profiles are active: standalone>
Hibernate: drop table if exists RegexRegisteredService
Hibernate: drop table if exists RegexRegisteredServiceProperty
Hibernate: drop table if exists RegisteredServiceImpl_Props
Hibernate: create table RegexRegisteredService (expression_type VARCHAR(15) DEFAULT 'ant' not null, id bigint not null auto_increment, access_strategy longblob, attribute_release longblob, description varchar(255), evaluation_order integer not null, informationUrl varchar(255), logo varchar(255), logout_type integer, logout_url varchar(255), mfa_policy longblob, name varchar(255) not null, privacyUrl varchar(255), proxy_policy longblob, public_key longblob, required_handlers longblob, serviceId varchar(255) not null, theme varchar(255), username_attr longblob, primary key (id)) type=MyISAM
Hibernate: create table RegexRegisteredServiceProperty (id bigint not null auto_increment, property_values longblob, primary key (id)) type=MyISAM
Hibernate: create table RegisteredServiceImpl_Props (AbstractRegisteredService_id bigint not null, properties_id bigint not null, properties_KEY varchar(255) not null, primary key (AbstractRegisteredService_id, properties_KEY)) type=MyISAM
Hibernate: alter table RegisteredServiceImpl_Props add constraint UK_i2mjaqjwxpvurc6aefjkx5x97 unique (properties_id)
Hibernate: alter table RegisteredServiceImpl_Props add constraint FK1xan7uamsa94y2451jgksjkj4 foreign key (properties_id) references RegexRegisteredServiceProperty (id)
Hibernate: alter table RegisteredServiceImpl_Props add constraint FK5ghaknoplphay7reury7n3vcm foreign key (AbstractRegisteredService_id) references RegexRegisteredService (id)
Hibernate: select count(abstractre0_.id) as col_0_0_ from RegexRegisteredService abstractre0_
2017-10-30 14:16:36,238 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] - <Table 'optoplusdb.RegexRegisteredService' doesn't exist>`
