### ISSUE TITLE
OAuth2 Authentication broken - created access tokens already expired

### ISSUE THREAD

**Issue by tk7r** [apereo/cas#2498]
I have included the following in my report:

- [x] CAS server version
CAS version: latest 5.1.0-RC3-SNAPSHOT (git master branch)

- [x] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
Tomcat 8.5.x, Linux

- [x] Steps to duplicate the problem along with your CAS settings and properties

configured a JPATicketRepository and include OAuth2-package in the war
method: using war overlay / gradle

The problem started a few days ago. i have seen the code reorganizations for oauth in the last days. 

The code does insert the oauth_token 2 times and the second time (because the token-name is the  primary key and must be unique)

[catalina.out.txt](https://github.com/apereo/cas/files/885506/catalina.out.txt)

see the log-file at line 225:
...
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "oauth_tokens_pkey"
  Detail: Key (id)=(AT-1-STnLb7iwoZCMcR6QHdjCd3NsKTm5SrkccOB) already exists.
...

looking at the OAuth20AccessTokenEndpointController::handleRequest method:
line 118: calls BaseOAuth20. generateAccessToken which calls this.ticketRegistry.addTicket(accessToken);
line 133: calls addTicketToRegistry() which calls this.ticketRegistry.addTicket(ticket);
when using a refresh token it would be called a third time.

there are multiple possible solutions:
- fix JPARepository to not blindly insert on save
or
- fix OAuth20AccessTokenEndpointController - because the other users of BaseOAuth20Controller don't seem to have multiple calls to ticketRegistry.addTicket ...

Where is the best place for the fix?

- [x] Stacktraces and CAS logs where appropriate.
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

**Comment by mmoayyed** [comment]
Probably `OAuth20AccessTokenEndpointController` is the better place.

**Comment by tk7r** [comment]
I have changed the call from addTicket to updateTicket which fixes the double insert problem. (see the attached patch)

BUT: when i want to use the token (like in the OAuth20UserProfileControllerController.handleRequest) the token gets deleted because it is expired?

Could you please point me in ANY direction how to analyze fix this issue?

[OAuth20AccessTokenEndpointController.patch.txt](https://github.com/apereo/cas/files/886857/OAuth20AccessTokenEndpointController.patch.txt)

**Comment by tk7r** [comment]
Taking out the JpaTicketRegistry and using the DefaultTicketRegistry works with the unmodified OAuth20AccessTokenEndpointController but calling the /profile endpoint returns only
{
  "error": [
    "expired_accessToken"
  ]
}

**Comment by tsschmidt** [comment]
Just chiming in that I am seeing this same thing with Hazelcast Registry.  Looking into it as well.

**Comment by mmoayyed** [comment]
I am not able to duplicate this with the current master. Does the issue still persist?

**Comment by tsschmidt** [comment]
I pulled the latest yesterday afternoon and it looks to be cleared up now.

On Apr 4, 2017 1:45 PM, Misagh Moayyed <notifications@github.com> wrote:

I am not able to duplicate this with the current master. Does the issue still persist?

**Comment by rkorn86** [comment]
I've currently exactly the same issue with  5.1.0.RC4-SNAPSHOT.
`curl -XPOST 'https://idp-dev.gfz-potsdam.de/cas/oauth2.0/accessToken?grant_type=password&client_id=XXXXX&username=XXXX&password=XXXXX'` returns `access_token=AT-2-AGKDPkhRYvGloTWwzxKwKn2ifbGPjWEio26&expires_in=7200`. Using it in a spring-boot application i get `{"error":"invalid_token","error_description":"AT-2-AGKDPkhRYvGloTWwzxKwKn2ifbGPjWEio26"}` when accessing it via `curl -H "Authorization: Bearer $TOKEN" 'https://sp.gfz-potsdam.de/test'`
This definitely worked on 5.1.0.RC2!

@mmoayyed Could you reopen this issue?

**Comment by rkorn86** [comment]
BTW: `curl https://idp-dev.gfz-potsdam.de/cas/oauth2.0/profile?access_token=$TOKEN` results in
```
{
  "error" : [ "expired_accessToken" ]
}
```

**Comment by rkorn86** [comment]
Log when creating access_token:
```
2017-04-07 14:45:49,182 DEBUG [org.apereo.cas.support.oauth.web.endpoints.BaseOAuth20Controller] - <Added access token [AT-4-YXGp0Hbb11GsJfkj9nwAF0yP0Tqfqf2XziF] to registry>
2017-04-07 14:45:49,182 DEBUG [org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController] - <Access token: [AT-4-YXGp0Hbb11GsJfkj9nwAF0yP0Tqfqf2XziF]>
2017-04-07 14:45:49,183 DEBUG [org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController] - <Service [org.apereo.cas.authentication.principal.SimpleWebApplicationServiceImpl@3db4993b[id=^http://ims.git.gfz-potsdam.de.*,originalUrl=^http://ims.git.gfz-potsdam.de.*,artifactId=<null>,principal=<null>,loggedOutAlready=false,format=XML]] is not able/allowed to receive refresh tokens>
2017-04-07 14:45:49,183 DEBUG [org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController] - <Generating access token response for [AT-4-YXGp0Hbb11GsJfkj9nwAF0yP0Tqfqf2XziF]>
2017-04-07 14:45:49,183 DEBUG [org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController] - <OAuth response type is [CODE]>
2017-04-07 14:45:49,184 DEBUG [org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController] - <Located response type as [CODE]>
```

Log when accessing oauth profile:
```
2017-04-07 14:46:08,262 DEBUG [org.apereo.cas.support.oauth.web.endpoints.OAuth20UserProfileControllerController] - <[access_token]: [AT-4-YXGp0Hbb11GsJfkj9nwAF0yP0Tqfqf2XziF]>
2017-04-07 14:46:08,263 ERROR [org.apereo.cas.support.oauth.web.endpoints.OAuth20UserProfileControllerController] - <Ticket granting ticket [null] parenting access token [AT-4-YXGp0Hbb11GsJfkj9nwAF0yP0Tqfqf2XziF] has expired>
2017-04-07 14:46:08,264 DEBUG [org.apereo.cas.ticket.registry.AbstractTicketRegistry] - <Removing ticket [AT-4-YXGp0Hbb11GsJfkj9nwAF0yP0Tqfqf2XziF] from the registry.>
```

**Comment by mmoayyed** [comment]
I think this is specific to grant-type being `password`. The AT somehow does not end up connected to the TGT.

**Comment by mmoayyed** [comment]
I gave this a shot and you're right; with grant type password the ticket granting ticket that should be issued for the AT is null. Which is why you get that error. 

Just for reference:

```bash
curl -X POST "https://mmoayyed.example.net:8443/cas/oauth2.0/accessToken?grant_type=password&client_id=client&username=casuser&password=Mellon"
```

and

```json
{
  "@class" : "org.apereo.cas.support.oauth.services.OAuthRegisteredService",
  "clientId": "client",
  "clientSecret": "test",
  "bypassApprovalPrompt": true,
  "serviceId" : ".*",
  "name" : "OAuth",
  "id" : 100
}

```

I have to look at this later.

**Comment by mmoayyed** [comment]
Fixed via https://github.com/apereo/cas/commit/d3ff46af5e79f2d031df4eaaa7b31eab0727cf12 and family.

**Comment by rkorn86** [comment]
Do I need to change my Service? With these fixes
```
{
  "@class": "org.apereo.cas.support.oauth.services.OAuthRegisteredService",
  "clientId": "PolhzOZBMj07qKnfEl8u",
  "clientSecret": "hh6bsGs3s3vDfA1PDgtsxF1qYpb7V7hjEnbHLlN8MbFywcdMIh7nKRDJmEUW",
  "bypassApprovalPrompt": true,
  "serviceId": "^http://ims.git.gfz-potsdam.de.*",
  "name": "IMS-Dev",
  "description": "Identity Management System - GitLab Pages"
  "id": 76197279983390320,
  "attributeReleasePolicy" : {
    "@class" : "org.apereo.cas.services.ReturnMappedAttributeReleasePolicy",
    "allowedAttributes" : {
      "@class" : "java.util.TreeMap",
      "cn" : "fullname",
      "sn" : "lastname",
      "givenName" : "firstname",
      "gfzSection" : "section",
      "mail" : "email",
      "gfzRole" : "roles",
      "gfzIdmPersonId" : "personId",
      "username" : "username",
      "title" : "title"
    }
  }
}
```
does not work and I get
```
2017-04-10 14:21:46,469 ERROR [org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController] - <Could not identify and extract access token request>
org.apereo.cas.services.UnauthorizedServiceException: Unauthorized Service Access. Service [^http://ims.git.gfz-potsdam.de.*] is not found in service registry.
        at org.apereo.cas.services.RegisteredServiceAccessStrategyUtils.ensureServiceAccessIsAllowed(RegisteredServiceAccessStrategyUtils.java:53) ~[cas-server-core-services-5.1.0-RC4-SNAPSHOT.jar:5.1.0-RC4-SNAPSHOT]
        at org.apereo.cas.services.RegisteredServiceAccessStrategyUtils.ensureServiceAccessIsAllowed(RegisteredServiceAccessStrategyUtils.java:69) ~[cas-server-core-services-5.1.0-RC4-SNAPSHOT.jar:5.1.0-RC4-SNAPSHOT]
        at org.apereo.cas.services.RegisteredServiceAccessStrategyUtils.ensurePrincipalAccessIsAllowedForService(RegisteredServiceAccessStrategyUtils.java:85) ~[cas-server-core-services-5.1.0-RC4-SNAPSHOT.jar:5.1.0-RC4-SNAPSHOT]
        at org.apereo.cas.DefaultCentralAuthenticationService.createTicketGrantingTicket(DefaultCentralAuthenticationService.java:363) ~[cas-server-core-5.1.0-RC4-SNAPSHOT.jar:5.1.0-RC4-SNAPSHOT]
        at org.apereo.cas.DefaultCentralAuthenticationService$$FastClassBySpringCGLIB$$b02e48f2.invoke(<generated>) ~[cas-server-core-5.1.0-RC4-SNAPSHOT.jar:5.1.0-RC4-SNAPSHOT]
```

Service is loaded:
```
2017-04-10 14:25:39,713 INFO [org.apereo.cas.services.DefaultServicesManager] - <Loaded [17] service(s) from [JsonServiceRegistryDao].>
2017-04-10 14:26:39,714 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Loading services from [JsonServiceRegistryDao]>
2017-04-10 14:26:39,719 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service [^http://ims.git.gfz-potsdam.de.*]>
2017-04-10 14:26:39,719 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service [https://idp-dev.gfz-potsdam.de/cas/idp/profile/SAML2/POST/SSO/Callback.+]>
2017-04-10 14:26:39,719 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service [https://idp-dev.gfz-potsdam.de/cas/oauth2.0/callbackAuthorize.*]>
...
```

**Comment by mmoayyed** [comment]
No, but note that `^http://ims.git.gfz-potsdam.de.*` is not exactly valid regex. You may need to skip the dots. May or may not be related.

**Comment by rkorn86** [comment]
`https://ims.git.gfz-potsdam.de.*` works, while `^https://ims.git.gfz-potsdam.de.*` does not. Does a leading `^` means: Interpret the following as regex?
BTW: `^https:\\/\\/ims\\.git\\.gfz\\-potsdam\\.\\de.*` does not work, too.

**Comment by mmoayyed** [comment]
>  Does a leading ^ means: Interpret the following as regex?

No. All serviceIds are regex patterns. That's essentially the only thing CAS supports. Note the relationship:

```
public class OAuthRegisteredService extends RegexRegisteredService { }
```

In other words, the pattern is always compiled as regex. Whether you put `^` in or not, is up to your choosing. 

What is the exact url that is sent to CAS? You either have a pattern that overrides things, or the pattern simply is a mismatch. Have you tried testing it with a regex tester?

**Comment by rkorn86** [comment]
There is no exact url, as im usin password granting type via `https://idp-dev.gfz-potsdam.de/cas/oauth2.0/accessToken?grant_type=password&client_id=PolhzOZBMj07qKnfEl8u&username=&password=`, so CAS must extract the service id itself via the given OAuth Client ID, which is rechecked against the service database. In my case the id has to match everytime, even if i enter some weird stuff as service id, as this is a true=true check, or am i wrong?

**Comment by mmoayyed** [comment]
Ah you're right; Sorry I keep forgetting that this is the password-grant. You're right on the OAuth client id, which is the part where CAS attempts to find a matching service that contains that client id. I think what's happening is the password-grant related code is building a "service" based on that regex id before CAS attempts to create a TGT. When the TGT is created, the service that is passed has the id of `^https://ims.git.gfz-potsdam.de.*` which is of course wrong. Reviewing.

**Comment by mmoayyed** [comment]
@rkorn86 How terribly upset would you be, if I asked you to actually provide a "service url" to CAS when making calls that deal with password-grant? We could make it happen without that url, but seeing how the AT is ultimately used in the context of an application which has some sort of identifier, I think it would be better to ask the application to identify itself. My proposal is to have the client, you, submit a `service` header matched against the definition. So you'll just add `--header "service: something-that-matches-the-registry"`. Would you be OK with that? 

This is purely a CAS complication/design issue, and one can perfectly argue that the service has already identified itself by providing `client` credentials. That's a perfectly valid argument, and I'll happily shut up with that BUT you do need to then change the serviceId in your definition to match the client id. I think the above change is cleaner, but your call really.

The issue is that OAuth service defns (as do all service defns) really need a service Id and in this particular grant-type that is simply absent which makes it difficult for CAS to perform authorization and access strategy rules. As I said, we can get by without this just fine and without creating security issues, but from a technical view, I wouldn't be exactly happy with the solution altogether :)

**Comment by mmoayyed** [comment]
Also to help explain why this worked before and not now: in older CAS releases the AT was given the ability to last a very long time beyond the lifetime of the TGT itself. Which meant that you could perfectly log out of CAS yet your AT would continue to be valid until its own expiration policy died. That is the behavior whose fix has caused a few complications for the password grant.

**Comment by mmoayyed** [comment]
Lets proceed with the header value for now and see how that goes. The more I look at this, the more I realize that option makes better sense than alternatives. If you (or anyone else) are are opposed to doing that, we can further debate this of course.

**Comment by rkorn86** [comment]
Is the additional header value RFC compliant? If so, it is ok for me, as long as this is really well documented as this is a big difference to other IdPs like Facebook, Google and co.

**Comment by mmoayyed** [comment]
I read over the RFC and I didn't see anything that would be contradictory. Pasting the relevant bits here:

```
   The authorization server MUST:

   o  require client authentication for confidential clients or for any
      client that was issued client credentials (or with other
      authentication requirements),

   o  authenticate the client if client authentication is included, and

   o  validate the resource owner password credentials using its
      existing password validation algorithm.

   Since this access token request utilizes the resource owner's
   password, the authorization server MUST protect the endpoint against
   brute force attacks (e.g., using rate-limitation or generating
   alerts).
```

In fact, the last paragraph is sort of encouraging, because we could say that we protect the endpoint by requiring a special header that could be used to authorize requests providing the side benefit of protecting against brute force attacks. 

See if the extra sentence here is sufficient please; we can certainly add more to clarify:
https://apereo.github.io/cas/development/installation/OAuth-OpenId-Authentication.html#resource-owner

**Comment by mmoayyed** [comment]
By the way, I am also considering to add the ability for an OAuth service definition to indicate what grant-types it supports. Right now, they all more or less support everything, and I think this would be a good addition to further lock things down if need be and have tighter control. I believe the same ability is offered by other OAuth IdPs as well. I don't know the exact extent of the changes just yet, but I can postulate that the default behavior of services may change to only allow the authz-code grant type. We might be able to make this change available for 5.1 but *not* break the default behavior, while for 5.2, we'd make the switch and change the default behavior. 

Sound good?

**Comment by tk7r** [comment]
Wouldn't it be better to define the allowed service inside service definition extracted from the client_id of the password grant request? something like a allowServiceList in the service definition?
What would be the default behaviour when no service-header is given - allow all? Anything else would break a generic OAuth2 client (not knowing anything about "the CAS way"), wouldn't it?

**Comment by mmoayyed** [comment]
The default behavior currently is prevent access, yes as generic OAuth2 clients are broken. That's the downside, but I submit it's a fairly "easy" thing for the client to accommodate?

 If I am understanding your proposal correctly, the `allowServiceList` option would basically indicate which services are allowed to talk to CAS via the password-grant? That's very good. That is in fact the intention of the serviceId field. Rather than providing an individual list, you specify a pattern by which services are allowed to talk. The issue here is, we need to get those clients to tell us who they are. 

Of course, we could simply say: "we already know your client id and we treat that as the service url", but that's much easier said than done. It will lead to a very technical hack to have CAS forcefully use the client id  as the service url only in the password-grant situation. 

The other option of course is to entirely remove this header noise, (or at least make it optional), but I think it's best to have it given that we can enforce authz rules more accurately and not have every client hit CAS repeatedly. The RFC is very loose on this point.

**Comment by tk7r** [comment]
Thank you for the explanation. I see your point. That's indeed a really fine dilemma.

IMHO i doubt the fairly easy for the client to send it part. I might be wrong but "generic" access libraries don't have a default way of sending additional headers with the oauth request. they would need to be changed in some way or another and cannot be used as is. - i see it as an additional adoption barrier for CAS.

I would like to see the service header as an optional, configurable method to the service. configuration options: allow the header method or not; set default when header not set.

Having the header would be great but not as a requirement you could easily miss when using cas for oauth2. How do other implementations of oauth2 servers handle this cas?

**Comment by mmoayyed** [comment]
Fair points on all counts; and I also understand the issue with client support. Breaking client behavior is generally a big no-no, but there may be compromises here and there. 

> I would like to see the service header as an optional, configurable method to the service. configuration options: allow the header method or not; set default when header not set.

I do favor this suggestion; with the caveat that we make the default behavior to *force the service-header*. I would like to make that a conscious decision for the CAS deployer to explicitly turn off this behavior. While perhaps "ill-advised", it will make it easier for less-than-flexible clients as you say. 

> How do other implementations of oauth2 servers handle this case?

I imagine they all more or less stick to the RFC and do not require at least a header, though some may impose additional requirements. The only other IdP I am most familiar with is the MitreID Connect server and I don't remember/know if there are any restrictions; probably there aren't. @rkorn86 may know better of course.

But, take into account that most other IdPs handle and support a single protocol that is OAuth, or OpenID Connect, etc. As such, they have a lot more freedom to make assumptions about how the API and components interact with each other. The CAS case is not so easy, because there are 7+ protocols and different versions of each all in the same application and this requires special care to determine how these things interact with each other. Thus you may find a few restrictions here and there which are purely technical complications and "design flaws" whose maintenance cost is lower than anything else in all likelihood in order to keep the entire platform sane.

**Comment by tk7r** [comment]
Sounds great to me!

**Comment by mmoayyed** [comment]
I thought about this some more and I realize it's best to keep the service header optional, and not breaking existing OAuth clients. This should keep @rkorn86 happy :) 

I'll push change upstream to accommodate this shortly. Thanks everyone for participating in the dialog!

**Comment by mmoayyed** [comment]
Closed via https://github.com/apereo/cas/commit/ce004e11d1a5d3c9376744abb1253c5079238ab2 and family.

This commit also adds support for supported grant and response types; though just the skeleton. Nothing is defined yet.
