### ISSUE TITLE
Consider supporting Zookeeper for config management via Spring Cloud

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2519]
Links:

- https://github.com/spring-cloud/spring-cloud-zookeeper/
- https://cloud.spring.io/spring-cloud-zookeeper/
- http://cloud.spring.io/spring-cloud-static/spring-cloud-zookeeper/1.0.3.RELEASE/

**Comment by hdeadman** [comment]
I had this working and I don't think it really required any changes to CAS. There were some dependency conflicts between the version of guava that CAS uses and the version used by curator but I think curator might have fixed that by "shading" guava in newer versions than I was using at the time. 

I ended up not using it because I think it required storing each property as a separate zookeeper entry. I was hoping to store a complete property file or yaml file in zookeeper. I could be wrong though, I mainly use Zookeeper for Solr and they store complete config files.

**Comment by mmoayyed** [comment]
This is extremely helpful. Thank you so much for the analysis. Do you think you might be able to prepare a guide or even a brief doc describing what you did to make this work?

**Comment by hdeadman** [comment]
I tried this with 5.1 RC3, in a maven overlay I added zookeeper dependencies via a profile (so it's easier to turn on or off):

```xml
<profile>
  <id>zookeeper</id>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-zookeeper-dependencies</artifactId>
        <version>1.0.3.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zookeeper-config</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zookeeper</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.curator</groupId>
      <artifactId>curator-client</artifactId>
      <version>2.12.0</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
      </exclusion>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.curator</groupId>
      <artifactId>curator-framework</artifactId>
      <version>2.12.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.curator</groupId>
      <artifactId>curator-recipes</artifactId>
      <version>2.12.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.zookeeper</groupId>
      <artifactId>zookeeper</artifactId>
      <version>3.4.10</version>
      <exclusions>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
        <exclusion>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
        </exclusion>
        <exclusion>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
</profile>

```
The dependency tree for the overlay project looks like this (when run with -Pzookeeper). 
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ cas-overlay ---
[INFO] org.apereo.cas:cas-overlay:war:1.0
[INFO] +- org.apereo.cas:cas-server-webapp-tomcat:war:5.1.0-RC3:runtime
[INFO] +- org.springframework.cloud:spring-cloud-starter-zookeeper-config:jar:1.0.3.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-zookeeper-config:jar:1.0.3.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-context:jar:1.1.2.RELEASE:compile
[INFO] |     \- org.springframework.security:spring-security-crypto:jar:4.0.4.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-zookeeper:jar:1.0.3.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-commons:jar:1.1.2.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-zookeeper-core:jar:1.0.3.RELEASE:compile
[INFO] +- org.apache.curator:curator-client:jar:2.12.0:compile
[INFO] +- org.apache.curator:curator-framework:jar:2.12.0:compile
[INFO] +- org.apache.curator:curator-recipes:jar:2.12.0:compile
[INFO] \- org.apache.zookeeper:zookeeper:jar:3.4.10:compile
[INFO]    +- jline:jline:jar:0.9.94:compile
[INFO]    \- io.netty:netty:jar:3.10.5.Final:compile
```

In bootstrap.properties I added this:
```
spring.cloud.zookeeper.connect-string=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
spring.cloud.zookeeper.enabled=true
spring.cloud.zookeeper.config.enabled=true
spring.cloud.zookeeper.config.root=cas/config
```

Then in zookeeper you would create nodes with values. Since the config root in this case is "cas/config",  under that you could have folders like "cas", "cas,dev", and "cas,local" where dev and local are spring profiles. Presumably you could also have folders like "application" too but I didn't try. To put a value in zookeeper, run:

```
zookeeper-client -server zookeeper1:2181
create /cas cas
create /cas/config cas
create /cas/config/cas cas
create /cas/config/cas/users casuser::Mellon,testuser::Junk,testuser2::user
```

I don't know why directories in zookeeper need values but zookeeper-client doesn't create things without a value afaik so I just put the value "cas" there.   

In cas.properties you could have something like:

```
cas.authn.accept.users=${users}
```

where ${users} gets the value of the contents of the zookeeper file cas/config/cas/users. You should be able to login as testuser/Junk.

**Comment by mmoayyed** [comment]
Outstanding! Thank you. 

I may end up documenting this in the official guides, though as you correctly put, there is nothing to do for CAS here. We may also expose a "helper" module that would auto-pull the zookeeper dependencies to make that step easier (Yes, there are folks who have no idea how to do that!) 

Perhaps, this might also provide an opportunity later on to enhance zookeeper functionality to support file-based settings vs individual, though I should note that almost all other CAS-supported sources do also expect individual settings.

**Comment by GiovanniMorelli** [comment]
Hi All, i'm trying this configuration... but doesn't work.. precisely cas read the new configuration when save on Zookeeper ... but don't work... for example i added the configuration as below... but the value of cas.authn.accept.users is empty... then when start cas i recived still the message STOP! CAS is configured to accept a static list of credentials for authentication.. Any idea?

**Comment by mmoayyed** [comment]
Thanks for the update. Let me start by saying "it doesn't work" is never a valid response to anything. You need to fully explain what you did and how you did it. Enumerate the exact set of steps so someone can verify. Furthermore, if `cas.authn.accept.users` is blank you should not be getting that STOP message, which means CAS is not reading your config correctly. Look closer.

**Comment by GiovanniMorelli** [comment]
@mmoayyed , thanks for you answer. I have did the configuration in cas 5.0.4 as above step by step. When i add a new configuration into Zookeeper,(for example : i have added in cas/config/cas/users empty value ) i saw in the console log of CAS : INFO [org.apereo.cas.configuration.CasConfigurationRebinder] - <Reloaded CAS configuration cas-org.apereo.cas.configuration.CasConfigurationProperties>, so i thought that cas is linked to zookeeper... but when i try to restart CAS i receive the message STOP!.. As you say .. CAS cannot read the correct configuration.. I'm trying a new way for check that CAS load the correctly property by Zookeeper

**Comment by mmoayyed** [comment]
Cool. I may have some time today to verify those steps and see how zookeeper really works. Never have had a chance to deal with it until now; I'll keep this thread posted, but in the meantime, please keep digging :)

**Comment by hdeadman** [comment]
I tested this configuration using an overlay with 5.1 RC3, not 5.0.4. I was
using zookeeper with 5.0.x at one point but ran into some issues with Guava
versions during the upgrade to 5.1 but this pom is using newer dependencies
that should be immune from Guava issues (so it might work in 5.0.4). You
should be seeing a bunch of zookeeper warnings if it is using zookeeper
(something about a Validator annotation) unless your global log level is
set to error. If it is set to error you should change it to warn. Make sure
the dependencies are in your war and make sure the
spring.cloud.zookeeper entries
are in bootstrap.properties. (I don't think you can add those spring cloud
properties to cas.properties, I think it needs to be in
bootstrap.properties).

**Comment by GiovanniMorelli** [comment]
@hdeadman  thank for you answer, i'm trying with 5.1.0-RC3.. i'll keep you update ..

**Comment by hdeadman** [comment]
@GiovanniMorelli 5.0 -> 5.1 is not a trivial upgrade unless you are just working with a simple overlay, even then I think there are differences with the way it reads property files that you might have to deal with.

I just tried running this zookeeper profile with 5.0.4 but it didn't work for me. I see the zookeeper dependencies in the cas.war and I see the entries in bootstrap.properties but I didn't see any warnings on startup (could be due to different spring-boot versions) and it did NOT appear to be using the property from zookeeper. I shut down zookeeper and when CAS started I got an error on the console that it couldn't connect to zookeeper so I know it is trying to use it. Not sure why the property isn't being read (in 5.0.4). It may not even be reading my local cas.properties b/c I could login as casuser/Mellon. It probably has to do with the difference in how 5.0 and 5.1 read their config.

In 5.1, where zookeper is working for me,  on startup I see messages like this:

```
 <The @ConfigurationProperties bean class org.springframework.cloud.zookeeper.ZookeeperProperties contains validation co
nstraints but had not been annotated with @Validated.>
2017-04-10 10:56:55,986 WARN [org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor] -
 <The @ConfigurationProperties bean class org.springframework.cloud.zookeeper.ZookeeperProperties contains validation co
nstraints but had not been annotated with @Validated.>
2017-04-10 10:56:55,986 WARN [org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor] -
 <The @ConfigurationProperties bean class org.springframework.cloud.zookeeper.ZookeeperProperties contains validation co
nstraints but had not been annotated with @Validated.>

←[36m
   __   ____      _      ____   __
  / /  / ___|    / \    / ___|  \ \
 | |  | |       / _ \   \___ \   | |
 | |  | |___   / ___ \   ___) |  | |
 | |   \____| /_/   \_\ |____/   | |
  \_\                           /_/

CAS Version: 5.1.0-RC3
CAS Commit Id: f1303c721e75fd2ed1ff63c7d992844eaaae52c1
CAS Build Date/Time: 2017-04-10T14:56:45.597Z
Spring Boot Version: 1.5.2.RELEASE
------------------------------------------------------------
System Date/Time: 2017-04-10T10:56:58.278
System Temp Directory: C:\Users\xyz\AppData\Local\Temp\
------------------------------------------------------------
Java Home: C:\Program Files\Java\jre1.8.0_112
Java Vendor: Oracle Corporation
Java Version: 1.8.0_112
JCE Installed: yes
------------------------------------------------------------
OS Architecture: amd64
OS Name: Windows 7
OS Version: 6.1
------------------------------------------------------------
Apache Tomcat Version: Apache Tomcat/8.5.12
------------------------------------------------------------

←[0m
2017-04-10 10:56:59,124 INFO [org.apereo.cas.configuration.config.CasCoreBootstrapStandaloneConfiguration] - <Configurat
ion files found at [.\etc\cas\config] are [[.\etc\cas\config\application.yml, .\etc\cas\config\cas.properties]]>
2017-04-10 10:56:59,177 INFO [org.apereo.cas.configuration.config.CasCoreBootstrapStandaloneConfiguration] - <Found and
loaded [31] setting(s) from [.\etc\cas\config]>
2017-04-10 10:56:59,177 INFO [org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration] - <Locate
d property source: PropertiesPropertySource [name='standaloneCasConfigService']>
2017-04-10 10:56:59,272 INFO [org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration] - <Locate
d property source: CompositePropertySource [name='zookeeper', propertySources=[ZookeeperPropertySource [name='cas/config
/cas,native'], ZookeeperPropertySource [name='cas/config/cas,standalone'], ZookeeperPropertySource [name='cas/config/cas
'], ZookeeperPropertySource [name='cas/config/application,native'], ZookeeperPropertySource [name='cas/config/applicatio
n,standalone'], ZookeeperPropertySource [name='cas/config/application']]]>
```

**Comment by mmoayyed** [comment]
I created https://issues.apache.org/jira/browse/CURATOR-398 to report the guava dependency issue; this must happen before we do anything in the codebase directly with zookeeper, though overlays probably can get by fine via perhaps including multiple copies of guava.

**Comment by hdeadman** [comment]
They are shading guava and doing it such a way that they rewrite the bytecode into their own package. I don't think it causes an issue anymore if you use the newer curator. They leave three guava interfaces that are in their public API alone but everything else is moved. Basically they don't use the guava that cas uses so it shouldn't cause a problem. I have used the Maven shade plugin to package lots of jars together in one jar but they are using a feature that actually hides the classes they are bundling from any other code. You just have to keep their old guava dependency out of cas (with an exclusion). They should probably list it as an optional dependency.

**Comment by mmoayyed** [comment]
I tried with curator 2.10 and then 3.3 (as the JIRA shows). Both exhibit the same problem, because we are forcing guava 21 and excluding 16 which is the  thing they need.  Once that JIRA is resolved, we can review again without resorting to further gymnastics.

**Comment by mmoayyed** [comment]
Just clarifying that I am not doing this at the overlay level. That will get by just fine by using a few tricks; those are what I am trying to avoid.

**Comment by hdeadman** [comment]
You need to use 2.12.

https://issues.apache.org/jira/browse/CURATOR-200
https://issues.apache.org/jira/browse/CURATOR-378

**Comment by mmoayyed** [comment]
Sweet! I'll try 2.12.0 in a bit. 3.3 exhibited the same behavior. At least this mirror shows it's still on 16.x: http://mvnrepository.com/artifact/org.apache.curator/curator-client/3.3.0

**Comment by hdeadman** [comment]
I do think they still reference 16.x so you would have to exclude that in
the overlay (make sure it isn't brought into the war via transitive
dependencies). They probably don't want to make their dependency "optional"
because they may need some version of guava in the classpath (for the three
interfaces in their API, but those are things that probably don't change in
Guava version to version). If they made it optional it could break some
apps that otherwise don't list guava as a dependency. If they bump up the
version to 21, some app that relied on the transitive dependency to bring
in Java but used Guava for other things in their app, could have an issue,
but that would be their fault for not explicitly listing their
dependencies.

**Comment by mmoayyed** [comment]
FWIW 2.12 works just fine. Thanks!

**Comment by mmoayyed** [comment]
Documented here https://apereo.github.io/cas/development/installation/Configuration-Server-Management.html#apache-zookeeper

**Comment by GiovanniMorelli** [comment]
Hi, i'm trying to configure Zookeeper as documentation, but when run maven i have this error : 

[ERROR] Failed to execute goal on project cas-overlay: Could not resolve dependencies for project org.apereo.cas:cas-overlay:war:1.0

I checked this JAR on https://mvnrepository.com/artifact/org.apereo.cas and  https://oss.sonatype.org/content/repositories/releases/org/apereo/cas/

but there isn't. sorry, there is another repository for cas?

Thanks in advantage

**Comment by mmoayyed** [comment]
Paste the full log please.

**Comment by mmoayyed** [comment]
As in, there needs to be more to `[ERROR] Failed to execute goal on project cas-overlay: Could not resolve dependencies for project org.apereo.cas:cas-overlay:war:1.0`

**Comment by GiovanniMorelli** [comment]
@mmoayyed  this is the log : 

[INFO] ------------------------------------------------------------------------
[INFO] Building cas-overlay 1.0
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.spring.io/milestone/commons-io/commons-io/maven-metadata.xml
Downloading: https://build.shibboleth.net/nexus/content/repositories/releases/commons-io/commons-io/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/commons-io/commons-io/maven-metadata.xml
Downloading: http://oss.sonatype.org/content/repositories/releases/commons-io/commons-io/maven-metadata.xml
Downloading: http://es-artifactory:8080/artifactory/repo/commons-io/commons-io/maven-metadata.xml
Downloaded: http://es-artifactory:8080/artifactory/repo/commons-io/commons-io/maven-metadata.xml (803 B at 1.3 KB/sec)
Downloading: http://oss.sonatype.org/content/repositories/releases/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.0.4/cas-server-core-configuration-cloud-zookeeper-5.0.4.pom
Downloading: https://build.shibboleth.net/nexus/content/repositories/releases/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.0.4/cas-server-core-configuration-cloud-zookeeper-5.0.4.pom
Downloading: https://repo.spring.io/milestone/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.0.4/cas-server-core-configuration-cloud-zookeeper-5.0.4.pom
Downloading: http://es-artifactory:8080/artifactory/repo/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.0.4/cas-server-core-configuration-cloud-zookeeper-5.0.4.pom
[WARNING] The POM for org.apereo.cas:cas-server-core-configuration-cloud-zookeeper:jar:5.0.4 is missing, no dependency information available
Downloading: http://oss.sonatype.org/content/repositories/releases/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.0.4/cas-server-core-configuration-cloud-zookeeper-5.0.4.jar
Downloading: https://build.shibboleth.net/nexus/content/repositories/releases/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.0.4/cas-server-core-configuration-cloud-zookeeper-5.0.4.jar
Downloading: https://repo.spring.io/milestone/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.0.4/cas-server-core-configuration-cloud-zookeeper-5.0.4.jar
Downloading: http://es-artifactory:8080/artifactory/repo/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.0.4/cas-server-core-configuration-cloud-zookeeper-5.0.4.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.652 s
[INFO] Finished at: 2017-04-11T11:50:20+02:00
[INFO] Final Memory: 25M/383M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cas-overlay: Could not resolve dependencies for project org.apereo.cas:cas-overlay:war:1.0: Could not find artifact org.apereo.cas:cas-server-core-configuration-cloud-zookeeper:jar:5.0.4
in sonatype-releases (http://oss.sonatype.org/content/repositories/releases/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by mmoayyed** [comment]
See:

```
[ERROR] Failed to execute goal on project cas-overlay: Could not resolve dependencies for project org.apereo.cas:cas-overlay:war:1.0: Could not find artifact org.apereo.cas:cas-server-core-configuration-cloud-zookeeper:jar:5.0.4
```

Then see the milestone assigned to this issue. I think that should explain it.  Also see the big giant red warning at the top of this page:
https://apereo.github.io/cas/development/installation/Configuration-Server-Management.html#apache-zookeeper

My experience as @hdeadman also explained exclusively dealt with 5.1. I personally have no plans to backport or experiment with 5.0.x.

**Comment by mmoayyed** [comment]
Also see the due date here: https://github.com/apereo/cas/milestone/47

**Comment by GiovanniMorelli** [comment]
thanks,.. i tried also with 5.1.0-RC3.. but i have the same error :

(Is it correct that the cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.jar doesn't exist on repository oss.sonatype.org? Because the others plugin exists)


Downloading: http://oss.sonatype.org/content/repositories/releases/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.1.0-RC3/cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.pom
Downloading: https://build.shibboleth.net/nexus/content/repositories/releases/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.1.0-RC3/cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.pom
Downloading: https://repo.spring.io/milestone/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.1.0-RC3/cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.pom
Downloading: http://es-artifactory:8080/artifactory/repo/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.1.0-RC3/cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.pom
[WARNING] The POM for org.apereo.cas:cas-server-core-configuration-cloud-zookeeper:jar:5.1.0-RC3 is missing, no dependency information available
Downloading: http://oss.sonatype.org/content/repositories/releases/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.1.0-RC3/cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.jar
Downloading: https://build.shibboleth.net/nexus/content/repositories/releases/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.1.0-RC3/cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.jar
Downloading: https://repo.spring.io/milestone/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.1.0-RC3/cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.jar
Downloading: http://es-artifactory:8080/artifactory/repo/org/apereo/cas/cas-server-core-configuration-cloud-zookeeper/5.1.0-RC3/cas-server-core-configuration-cloud-zookeeper-5.1.0-RC3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.203 s
[INFO] Finished at: 2017-04-11T14:38:09+02:00
[INFO] Final Memory: 36M/513M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cas-overlay: Could not resolve dependencies for project org.apereo.cas:cas-overlay:war:1.0: Could not find artifact org.apereo.cas:cas-server-core-configuration-cloud-zookeeper:jar:5.1.0-
RC3 in sonatype-releases (http://oss.sonatype.org/content/repositories/releases/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


![image](https://cloud.githubusercontent.com/assets/17708511/24909822/dd9db6d8-1ec5-11e7-8124-a1c2c4ee776a.png)

**Comment by hdeadman** [comment]
You would need to try 5.1.0-RC4-SNAPSHOT as the versoni if you want to use
the new plugin. I haven't tried it.

**Comment by mmoayyed** [comment]
You are not paying attention to me, or maybe I am not explaining things correctly. Let me explain:

1. The functionality you are after, and what is described here is available in 5.1.0.RC4. See the milestone assigned to this issue.
2. If you review the project's release schedule, you realize RC4 is not yet released and is still in development.
3. You are welcome to continue experimenting with the 5.0.x line; this issue does not apply to that release.

So you can either wait for the release, switch to SNAPSHOTs of RC4 or build the codebase from source.

**Comment by GiovanniMorelli** [comment]
Hi @mmoayyed @hdeadman   :) thanks, now i understand. So i continue to work with 5.0.4. Thanks

**Comment by GiovanniMorelli** [comment]
Hi All, i have created the "cas-server-core-configuration-cloud-zookeeper" in cas 5.0.4 as cas-server-core-configuration-cloud-mongo and work it.

When start the CAS , it read all properties under zookeeper's path : /cas/config/cas, without to configure cas.properties.

To start this configuration , need to add this string in bootstrap.properties : "cas.spring.cloud.zookeeper.uri = localhost:2181".

Now I'm trying to update CAS 5.1.0-RC4-SNAPSHOT for commit new classes... but when run gradle on root project i receive this error:

Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'java-library' not found.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\gmorelli\Downloads\CAS 5.1.0_R4\cas\build.gradle' line: 116

* What went wrong:
A problem occurred evaluating root project 'cas-server'.
> Plugin with id 'java-library' not found.


if you want i can attach the classes..
