### ISSUE TITLE
CAS 5.0.5 password warning login?execution= too long for Windows IE/Edge browsers

### ISSUE THREAD

**Issue by ddb79** [apereo/cas#2869]
- [X] CAS server version: CAS 5.0.5
- [X] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc): TOMCAT
- [X] Steps to duplicate the problem along with your CAS settings and properties: SEE TEXT BELOW
- [X] Stacktraces and CAS DEBUG logs where appropriate.: SEE ATTACHMENTS BELOW
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/ or attached to the issue.

Adding this as an issue, as we are hoping to track this issue with a formal code fix solution, as this issue is blocking our production deployment. We are hoping for a solution that will produce a shorter URL length such that all browsers will work with the CAS continue function as described below.

Are there any CAS configuration alternatives to this? We are reaching out to the CAS community for possible solutions to this problem.

We have cas.authn.ldap[0].passwordPolicy.warningDays=5 firing a password change warning from casLoginMessageView.html (SEE ATTACHED casLoginMessageView.html)

When we press continue, then the URL fires with login?execution=... being too long for the Windows IE/Edge browsers, which seem to truncate the URL out at around 10k bytes. For the browsers that are successful processing the url, then that URL length is around 19k (SEE ATTACHED localhost_access_log.2017-08-21.txt)

Also, attaching a corresponding TOMCAT CATALINA LOG that corresponds to the localhost_access_log (SEE ATTACHED catalina-daemon-2017-08-21.out.txt).

Thank you, Duane.Booher@nau.edu

[casLoginMessageView.html.txt](https://github.com/apereo/cas/files/1243237/casLoginMessageView.html.txt)
[casLoginMessageView.html.txt](https://github.com/apereo/cas/files/1243241/casLoginMessageView.html.txt)
[catalina-daemon-2017-08-21.out.txt](https://github.com/apereo/cas/files/1243244/catalina-daemon-2017-08-21.out.txt)
[localhost_access_log.2017-08-21.txt](https://github.com/apereo/cas/files/1243247/localhost_access_log.2017-08-21.txt)

**Comment by mmoayyed** [comment]
Based on my current reading of this file:
https://github.com/apereo/cas/blob/5.0.x/webapp/cas-server-webapp/src/main/resources/templates/casLoginMessageView.html

The redirect is switched to be a POST and not a GET to avoid this issue, and this is something that is likely fixed in releases beyond 5.0.5. As discussed, you're encouraged to upgrade and then diagnose and fix other issues that arise. Alternatively, you can pull down that file into your overlay and let it solve that problem though that's probably not a very good approach because it will only and simply complicate your upgrade processes even further.

**Comment by ddb79** [comment]
Would this be fixed in 5.0.x or 5.1.x?

**Comment by ddb79** [comment]
I was able to copy the latest 5.0.x version of casLoginMessageView.html on top of my 5.0.5 overlay, and this fixes this problem. Can I assume that this temporary workaround has no other dependencies?

My goal is to somehow fix the cas/proxy issue so that I can upgrade to the latest 5.0.x version.

**Comment by mmoayyed** [comment]
Yes that should do it. There are no other dependencies.

**Comment by mmoayyed** [comment]
And if by this you mean the change to post it's likely fixed in both versions. Any change that is applied to anything before master is brought for forward to all other branches but not necessarily the other way around.

Also have a look at the maintenance policy too. That might influence your decision a bit.
