### ISSUE TITLE
Themed views is  broken in CAS >= 5.1

### ISSUE THREAD

**Issue by karlbanke** [apereo/cas#2877]
We are setting up a CAS System and are using themed views. What worked like a charm in CAS 4.x does not work at all in CAS 5.1/5.2-RC1. Put together, what we see is that.

(a) When creating templates and fragments for a theme under 
/resources/templates/themeA
/resources/templates/themaA/fragments
The fragments defined under the fragments directory are never USED. Instead fragments from 
/resource/templates/fragments 
i.e. the default fragments are used. 
However the fragments must be PRESENT there anyway. 
(b) When switching between services, one using a theme and one not using a theme, the outcome is not deterministic. Sometimes you get the templates from the correct theme and the css file from the other, sometimes the other way round. Sometimes it does not work at all.
(c)  Artifact built from the same codebase behaves notably different after subsequent maven builds.

I don't have the resources to dive into how templating and theming actually works under the hood, but it seems to be totally broken at the moment. I think what we are expecting here might be duplictae of https://github.com/apereo/cas/issues/2861

**Comment by mmoayyed** [comment]
Can you put together a CAS overlay that demonstrates this problem?

**Comment by frett** [comment]
I just did work on porting several custom themes to CAS 5.1.x for my local deployment

(a) everything in thymeleaf appears to be in a single namespace. so instead of using "fragments/loginpage" you would use "themeA/fragments/loginpage".

(b) this is because of how CAS swaps out the template location in the view resolver coupled with view resolver caching. I worked up a local solution with a custom ViewResolver that is on my list to refactor and push upstream. A temporary work around is to disable Thymeleaf caching, but this has performance impact.
