### ISSUE TITLE
CAS 5.2.0-RC3 Transitive dependencies in overlay missing

### ISSUE THREAD

**Issue by karlbanke** [apereo/cas#2899]
When porting our project using the overlay method from 5.2.0-RC1 to 5.2.0-RC3-SNAPSHOT I noticed that the transitive compile dependencies are gone. When defining classes in the overlay that need to override a specific cas class or that derive from one or that use one, I now need to include the dependency right in the project. Is this intended?

**Comment by mmoayyed** [comment]
Yes  It is. You might be able to leverage the cas bom. What dependencies are these?

**Comment by karlbanke** [comment]
Various. cas-server-support-mongo-ticket-registry, cas-server-core-util, cas-server-webapp-config, cas-server-core-tickets and various others including apache-common-lang3. 

We had to override the files, because (for example) they were missing critical information for proper mongo db connection, such as specification of ssl, cluster definition and others. 

Also we had to properly divide the MongoDB connection to the ticket registry from the one made to the service registry. 

We also had to override the MongoProfileService from pac4j in order to include various additional checks during authentication (e.g. is the user locked or is the users email validated).

That the transitive dependencies are missing is a version conflict mismatch waiting to happen. What is the rationale? It takes a lot of the power of the overlay method away.

**Comment by mmoayyed** [comment]
The rationale is to prevent leakage and as a side effect, [sort of] prevent unintentional(!) custom work where custom equals bug or improvement. Rather than overriding files, you need to reconsider your approach and file PRs to add the missing bits you need with config. Otherwise, chances are you break again very quickly the very next time you upgrade because those things are added or changed. 

Dont take this the wrong way, but *stop writing code* :) write it where it belongs.

**Comment by mmoayyed** [comment]
I would add that if the PR process is rather difficult, you're more than welcome to attach plain .java files here, or post to the list and I/others would be happy to review, adjust and merge immediately. The goal of the overlay is to keep it super small and override truly what's needed. Overriding .class files is prone to error, and note that we make no guarantees in terms of what dependency is added, made available or removed specially in cases of major/minor versions. All bets are off. If you want to attach your changes here, I'd be happy to review and access as all of your "custom" work are fine candidates for contributions.

**Comment by mmoayyed** [comment]
Finally, I also believe that the mongodb support when it comes services vs tickets is separated out and you shouldn't have to do anything to make that work anymore, or it's a bug that needs reviews and contributions, if any.

**Comment by karlbanke** [comment]
At the end of the day, an overlay where you should not overlay by replacing classes makes IMHO very little sense ;-). When all you want to achieve is to be able to replace templates and static resources there are much better ways. 

I also agree that you are right in noting that it would be better to file a request for change or a bug report and see that resolved. Unfortunately, the ticket handling and release information that you apply gives very little information about when an issue will be fixed and when it is really fixed. Although I have to admit that you are in general very quick! 

Also the CAS project is huge and applies an somewhat unfamiliar build process. No problem of course, but when I submit some changes that creates a lot of overhead (and does not fix the immediate problem ;-)).

Attached find our MongoDB related configuration changes that enable us the use ssl and cluster connectivity. 
[mongorelated.zip](https://github.com/apereo/cas/files/1266828/mongorelated.zip)

**Comment by mmoayyed** [comment]
Excellent, thank you. I will review and get back to you. 

There should be hopefully adequate documentation that describes how to set up a dev environment and go about making changes to the core. If you have any trouble in that area, I would wholeheartedly welcome questions and suggestions and I would love to help you and others get going quickly with the patch process. The goal is to have you catch fish and we'd like to do that **as fast as possible** to help you along the dev path. That's how the project you run and deloy today came into existence. Laundry doesn't fold itself.

And I would emphasize and suggest again that, you are to never replace .class files. Speaking from doing this for a living, that approach is riddled with issues. You CAN replace classes; However if you end up doing things on your own, then you would be on your own :) and limited to your own tooling and any and all headaches that ensue. As I say, the overlay approach is accidentally designed to keep your overlay super small to the changes you absolutely do need. Every time you feel like you need to write code to fix a bug or add an enhancement, you need to think about how to contribute that patch to CAS itself and be rid of it in your overlay. I deal with many project deployments during the week where I end up doing the same exact thing because I see folks lead their deployment in lots of issues. There are legitimate use cases for truly custom behavior and implementations and from time to time I run into those myself, but most commonly, the problem I need to solve is "we decided to overlay this class because we needed this config here and it didn't do that". Yes, it most certainly doesn't do everything, but it can :) as soon as you (and I helping you as much as I can) step into it.

Sorry about the rant. I'll try to add these suggestions to the docs somewhere so as to make this suggestion very clear should folks decide to venture down this path.

PS Of course, if you have other suggestions on how to make an overlay process more comfortable, by all means.

**Comment by mmoayyed** [comment]
Finally, if you are not in already, I'd recommend that you either join the mailing list or the chatroom:
https://apereo.github.io/cas/Support.html#chat-room

The chatroom certainly works faster, if you need to check on the status of something getting or being fixed....and watch the changelog: https://apereo.github.io/2017/09/15/520rc3-release/ here on the release status and updates. It's a  live post.

**Comment by mmoayyed** [comment]
Added the settings, pushed. Try again please the very next snapshot goes out, later this afternoon most likely. For the most part, I see the addition of 3 new settings, and I see how you managed to create separate connections for the service and ticket registry the latter is of course unnecessary now.

**Comment by mmoayyed** [comment]
Note added here https://apereo.github.io/2017/09/15/520rc3-release/#minors
